#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot the impact of gateway concurrency (and adaptive load limits) for the dual-BS sweeps.

This script scans the JSON files generated by `scripts/run_gateway_sweep.py`
when the `--gateway-concurrency` flag is enabled.  For each JSON it selects
the configuration with the highest mean end-to-end PDR, extracts diagnostic
statistics (CH→BS PDR, mean load limit, fraction of rounds clamped to L=1,
effective concurrency usage), and renders a bar/line plot so that the paper
can highlight why concurrent uplinks currently bring little benefit.
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np


def parse_case_list(values: List[str]) -> List[Tuple[str, Path]]:
    """
    Parse CLI arguments of the form "label:path/to/file.json".
    """
    cases: List[Tuple[str, Path]] = []
    for item in values:
        if ":" not in item:
            raise ValueError(f"Expected label:path format, got '{item}'")
        label, path_str = item.split(":", 1)
        path = Path(path_str.strip()).expanduser().resolve()
        if not path.exists():
            raise FileNotFoundError(path)
        cases.append((label.strip(), path))
    return cases


def summarize_json(path: Path) -> Dict[str, float]:
    """
    Extract the best-PDR configuration and summarize diagnostic information.
    """
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    best_key = None
    best_pdr = -1.0
    for key, entry in data.items():
        pdr = entry.get("stats", {}).get("pdr_end2end", {}).get("mean")
        if pdr is None:
            continue
        if pdr > best_pdr:
            best_pdr = float(pdr)
            best_key = key
    if best_key is None:
        raise RuntimeError(f"No valid entries in {path}")
    entry = data[best_key]
    stats = entry["stats"]
    runs = entry["runs"]

    def avg(field: str) -> float:
        values = [r.get(field) for r in runs if r.get(field) is not None]
        return float(sum(values) / len(values)) if values else 0.0

    def avg_trace(func) -> float:
        values = []
        for r in runs:
            trace = r.get("gateway_limit_trace")
            if trace:
                values.append(func(trace))
        return float(sum(values) / len(values)) if values else 0.0

    def frac_limit_one(trace: List[int]) -> float:
        if not trace:
            return 0.0
        ones = sum(1 for v in trace if v <= 1)
        return ones / len(trace)

    summary = {
        "key": best_key,
        "pdr_e2e": float(stats["pdr_end2end"]["mean"]),
        "pdr_ch_bs": float(stats["ch_to_bs_pdr"]["mean"]),
        "energy": float(stats["energy"]["mean"]),
        "limit_final": avg("gateway_limit_final"),
        "limit_mean": avg_trace(lambda tr: sum(tr) / len(tr)),
        "limit_frac_one": avg_trace(frac_limit_one),
        "concurrency_used": avg("gateway_concurrency_avg"),
    }
    return summary


def build_panel(ax, twin, label: str, cases: List[Tuple[str, Dict[str, float]]]):
    twin.set_ylabel("Avg. $L_{gw}$ during run")
    twin.set_ylim(0.8, 4.2)
    twin.grid(False)
    twin.grid(False)

    indices = np.arange(len(cases))
    width = 0.6
    bars = ax.bar(
        indices,
        [c[1]["pdr_e2e"] for c in cases],
        width=width,
        color="#4C72B0",
        alpha=0.85,
    )
    ax.set_ylim(0, max([c[1]["pdr_e2e"] for c in cases]) * 1.35)
    ax.set_ylabel("Best $\\mathrm{PDR}_{e2e}$")
    ax.set_xticks(indices)
    ax.set_xticklabels([c[0] for c in cases])
    ax.set_title(label)

    line = twin.plot(
        indices,
        [c[1]["limit_mean"] for c in cases],
        marker="o",
        color="#DD8452",
        linewidth=2,
        label="Avg. dynamic $L_{gw}$",
    )[0]
    twin.set_ylabel("Avg. $L_{gw}$ during run")
    twin.set_ylim(0.8, 4.2)

    for idx, bar in enumerate(bars):
        case = cases[idx][1]
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            bar.get_height() + 0.002,
            f"PDR {case['pdr_e2e']:.3f}\nCH→BS {case['pdr_ch_bs']:.3f}",
            ha="center",
            va="bottom",
            fontsize=8,
        )
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            0.001,
            f"avg $L_{{gw}}$={case['limit_final']:.1f}\n"
            f"mean limit={case['limit_mean']:.2f}\n"
            f"$L=1$ frac={case['limit_frac_one']:.2f}\n"
            f"used concurrency={case['concurrency_used']:.1f}",
            ha="center",
            va="bottom",
            fontsize=7,
        )
    return bars, line


def main():
    parser = argparse.ArgumentParser(description="Plot gateway concurrency diagnostics.")
    parser.add_argument(
        "--uniform300",
        nargs="+",
        default=[
            "conc2:results/gateway_sweep_uniform300_dualbs_concurrency2.json",
            "conc4:results/gateway_sweep_uniform300_dualbs_concurrency4.json",
        ],
        help="Label:path pairs for Uniform-300 concurrency sweeps.",
    )
    parser.add_argument(
        "--uniform500",
        nargs="+",
        default=[
            "conc2:results/gateway_sweep_uniform500_dualbs_concurrency2.json",
            "conc4:results/gateway_sweep_uniform500_dualbs_concurrency4.json",
        ],
        help="Label:path pairs for Uniform-500 concurrency sweeps.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="results/plots/paper_gateway_concurrency_effect.pdf",
    )
    parser.add_argument(
        "--output-svg",
        type=str,
        default="results/plots/paper_gateway_concurrency_effect.svg",
    )
    args = parser.parse_args()

    uniform300_cases = [
        (label, summarize_json(path)) for label, path in parse_case_list(args.uniform300)
    ]
    uniform500_cases = [
        (label, summarize_json(path)) for label, path in parse_case_list(args.uniform500)
    ]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5), sharey=True)
    bars0, line0 = build_panel(
        axes[0], axes[0].twinx(), "Uniform-300 dual BS", uniform300_cases
    )
    bars1, line1 = build_panel(
        axes[1], axes[1].twinx(), "Uniform-500 dual BS", uniform500_cases
    )
    fig.legend(
        [bars0[0], line0],
        ["Best $\\mathrm{PDR}_{e2e}$", "Avg. dynamic $L_{gw}$"],
        loc="upper center",
        ncol=2,
        bbox_to_anchor=(0.5, 1.08),
        frameon=False,
    )
    fig.tight_layout(rect=[0, 0, 1, 0.95])

    out_pdf = Path(args.output)
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_pdf, bbox_inches="tight")
    out_svg = Path(args.output_svg)
    fig.savefig(out_svg, bbox_inches="tight")
    print(f"[DONE] Saved figure to {out_pdf} and {out_svg}")


if __name__ == "__main__":
    main()
